name: OME  Website
markdown: kramdown

url: https://ome.github.io
repository: openmicroscopy/www.openmicroscopy.org
baseurl: /www.openmicroscopy.org

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
paginate: 10
paginate_path: "/announcements/page:num/"

future: true

bf:
 version: 6.5.0

omero:
 version: 5.6.1
 majorversion: 5.6
 build: b225
 insight:
  version: 5.5.11
 matlab:
  version: 5.5.3

omecommoncpp:
  version: 5.5.0

omemodel:
  version: 6.0.0

omeqtwidgets:
 version: 5.4.3

omefiles:
 version: 0.5.0
 build: 25

omecmakesuperbuild:
 version: 0.5.0
